library(data.table)
library(ggplot2)

source('analysis.R', local = TRUE)

# Filter for videos that have hit the 48-hour maturity mark
videos_48h <- d[, .(max_age = max(launch_age)), by = video_id][max_age >= 48, video_id]
filtered_data <- d[video_id %in% videos_48h]

# Aggregate to channel level to show form
channel_summary <- filtered_data[, .(
  avg_peak_velocity = mean(peak_velocity, na.rm = TRUE),
  avg_bass_p = mean(bass_p, na.rm = TRUE),
  avg_bass_q = mean(bass_q, na.rm = TRUE),
  avg_engagement = mean(engagement, na.rm = TRUE),
  videos_tracked = uniqueN(video_id)
), by = channel_id]

dir.create("report_assets", showWarnings = FALSE)

# 1. Peak Velocity
p1 <- ggplot(channel_summary, aes(x = reorder(channel_id, avg_peak_velocity), y = avg_peak_velocity, fill = avg_peak_velocity)) +
  geom_col() +
  coord_flip() +
  scale_fill_viridis_c(option = "plasma", end = 0.9) +
  theme_minimal() +
  labs(
    title = "Average Peak Velocity (VPH) by Channel",
    subtitle = "Higher values indicate a stronger 'Flash' impact during launch.",
    x = "Channel ID",
    y = "Average Peak Views Per Hour",
    fill = "Velocity"
  )
ggsave("report_assets/velocity_chart.png", plot = p1, width = 10, height = 6)

# 2. Bass Scatter
p2 <- ggplot(channel_summary, aes(x = avg_bass_p, y = avg_bass_q, size = avg_peak_velocity, color = channel_id)) +
  geom_point(alpha = 0.8) +
  scale_size(range = c(5, 15)) +
  theme_minimal() +
  labs(
    title = "Influencer Adoption Profiles",
    subtitle = "Size of bubble indicates Peak View Velocity",
    x = "Innovation Coefficient (p) - Core Following",
    y = "Imitation Coefficient (q) - Algorithmic Virality",
    color = "Channel ID",
    size = "Peak Velocity"
  ) +
  theme(legend.position = "right")
ggsave("report_assets/bass_scatter.png", plot = p2, width = 10, height = 6)

# 3. Engagement Boxplot
p3 <- ggplot(filtered_data, aes(x = reorder(channel_id, engagement, FUN = median, na.rm=TRUE), y = engagement, fill = channel_id)) +
  geom_boxplot(alpha = 0.7, outlier.shape = NA) +
  geom_jitter(width = 0.2, alpha = 0.5, size = 1) +
  coord_flip() +
  theme_minimal() +
  labs(
    title = "Engagement Distribution by Channel",
    subtitle = "Data points represent individual videos",
    x = "Channel ID",
    y = "Weighted Engagement Ratio (%)"
  ) +
  theme(legend.position = "none")
ggsave("report_assets/engagement_box.png", plot = p3, width = 10, height = 6)

# Generate HTML
html <- '
<!DOCTYPE html>
<html>
<head>
<title>Influencer Campaign Metrics</title>
<style>
  body { font-family: sans-serif; max-width: 1000px; margin: 0 auto; padding: 20px; line-height: 1.6; }
  img { max-width: 100%; height: auto; margin-bottom: 2rem; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
  h1, h2 { color: #333; }
  .section { margin-bottom: 3rem; }
</style>
</head>
<body>
<h1>Influencer Campaign Metrics: Velocity & Adoption Analysis</h1>
<p>This report tracks the performance dynamics of influencers active in the current tracking window. The dataset is filtered to only include videos that have been actively tracked for at least 48 hours.</p>

<div class="section">
  <h2>1. Peak Velocity (V_max)</h2>
  <p><strong>What this measures:</strong> View Velocity measures the raw "Hype" and FOMO generated by the creator. It indicates how many viewers have notifications turned on and watch immediately.</p>
  <img src="report_assets/velocity_chart.png" alt="Average Peak Velocity">
</div>

<div class="section">
  <h2>2. Adoption Profiles (Loyalists vs. Viral Engines)</h2>
  <p><strong>What this measures:</strong> Mapping Bass Diffusion metrics to determine how the influencers audience grows: Coefficient of Innovation (p) driven by dedicated followers vs Coefficient of Imitation (q) driven by algorithm/sharing.</p>
  <img src="report_assets/bass_scatter.png" alt="Adoption Profiles">
</div>

<div class="section">
  <h2>3. Weighted Engagement & Intent</h2>
  <p><strong>What this measures:</strong> Ratio of (Likes + 2x Comments) / Views. High engagement strongly correlates with viewer satisfaction, intent to purchase, and CTR.</p>
  <img src="report_assets/engagement_box.png" alt="Engagement Distribution">
</div>

</body>
</html>
'
writeLines(html, "report.html")
